name: Python CI with Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build Docker image
      uses: docker/build-push-action@v6.16.0
      with:
        context: .
        file: Dockerfile
        push: true
        tags: |
          my-python-app:latest
          my-python-app:${{ github.sha }}

    - name: Run Unit Tests
      run: docker run my-python-app pytest

    - name: Run Python Script
      uses: jannekem/run-python-script-action@v1.7
      with:
        script: |
          python my_script.py
        fail-on-error: true
        util: true
