name: Python CI with Linting

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run Flake8 linter
        run: |
          echo "⚙️ Running Flake8..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Done
        run: echo "✅ Workflow complete!"
