name: Python CI with Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored as a secret
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored as a secret

    - name: Build Docker image
      uses: docker/build-push-action@v6.16.0
      with:
        context: .
        file: .devcontainer/Dockerfile  # Update this line to point to the Dockerfile in the .devcontainer folder
        push: true
        tags: |
          ${{ secrets.DOCKER_USERNAME }}/my-python-app:latest  # Include your Docker Hub username
          ${{ secrets.DOCKER_USERNAME }}/my-python-app:${{ github.sha }}

    - name: Run Unit Tests
      run: docker run ${{ secrets.DOCKER_USERNAME }}/my-python-app pytest

    - name: Run Python Script
      uses: jannekem/run-python-script-action@v1.7
      with:
        script: |
          python my_script.py
        fail-on-error: true
        util: true
